DROP DATABASE IF EXISTS shop;
CREATE DATABASE shop CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

DROP USER IF EXISTS 'suser'@'%';
CREATE USER IF NOT EXISTS 'suser'@'%' IDENTIFIED BY 'spass';
GRANT ALL PRIVILEGES ON shop.* TO 'suser'@'%';
FLUSH PRIVILEGES;

USE shop;

SET SESSION FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS item;

CREATE TABLE item (
    id VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    price INT NOT NULL,
    stock INT NOT NULL,
    PRIMARY KEY (id)
);

SET SESSION FOREIGN_KEY_CHECKS = 1;